// This file is part of kanjokamoku — MIT License
// https://github.com/tsubasagit/kanjokamoku

import type { ClassificationRule } from "./types";

/**
 * 宿泊費 → 旅費交通費(511)
 * ビジネスホテル・高級ホテル・予約サイトからの請求を分類する。
 * counterAccount: クレジットカード(203)
 */
export const ACCOMMODATION_RULES: ClassificationRule[] = [
  // ── ビジネスホテル ──
  {
    name: "東横イン",
    pattern: "東横イン",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "東横INN",
  },
  {
    name: "アパホテル",
    pattern: "アパホテル",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "APA Hotel",
  },
  {
    name: "ルートイン",
    pattern: "ルートイン",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "スーパーホテル",
    pattern: "スーパーホテル",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "コンフォートホテル",
    pattern: "コンフォートホテル",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "ドーミーイン",
    pattern: "ドーミーイン",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "共立メンテナンス",
  },
  {
    name: "リッチモンドホテル",
    pattern: "リッチモンドホテル",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "三井ガーデンホテル",
    pattern: "三井ガーデンホテル",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "ダイワロイネットホテル",
    pattern: "ダイワロイネット",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },

  // ── 高級ホテル ──
  {
    name: "ヒルトン",
    pattern: "ヒルトン",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    note: "Hilton Hotels — 会議費の可能性あり",
  },
  {
    name: "マリオット",
    pattern: "マリオット",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    note: "Marriott International",
  },
  {
    name: "ハイアット",
    pattern: "ハイアット",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    note: "Hyatt Hotels",
  },
  {
    name: "シェラトン",
    pattern: "シェラトン",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    note: "Sheraton（Marriott系列）",
  },
  {
    name: "ANAインターコンチネンタル",
    pattern: "インターコンチネンタル",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    note: "IHG ANA Hotels",
  },

  // ── 予約サイト ──
  {
    name: "楽天トラベル",
    pattern: "楽天トラベル",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    note: "宿泊以外に交通手配も含む場合あり",
  },
  {
    name: "じゃらん",
    pattern: "じゃらん",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    note: "リクルート じゃらんnet",
  },
  {
    name: "Booking.com",
    pattern: "Booking.com",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
  },
  {
    name: "Expedia",
    pattern: "Expedia",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.85,
    note: "航空券も含む場合あり",
  },
  {
    name: "Hotels.com",
    pattern: "Hotels.com",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
  },
  {
    name: "Agoda",
    pattern: "Agoda",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
  },
  {
    name: "一休.com",
    pattern: "一休",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.85,
    note: "一休.com — レストラン予約の可能性もあり",
  },
  {
    name: "Airbnb",
    pattern: "Airbnb",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    note: "民泊サービス",
  },
];
