// This file is part of kanjokamoku — MIT License
// https://github.com/tsubasagit/kanjokamoku

import type { ClassificationRule } from "./types";

/**
 * 広告宣伝費 → 広告宣伝費(521)
 * 広告プラットフォーム・PR・SEOツール・印刷会社を分類する。
 * counterAccount: クレジットカード(203)
 */
export const ADVERTISING_RULES: ClassificationRule[] = [
  // ── 広告プラットフォーム ──
  {
    name: "Google Ads",
    pattern: "Google Ads",
    matchType: "contains",
    accountCode: "521",
    accountName: "広告宣伝費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "Google広告（旧AdWords）",
  },
  {
    name: "Meta Ads",
    pattern: "Meta Ads",
    matchType: "contains",
    accountCode: "521",
    accountName: "広告宣伝費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "Facebook / Instagram広告",
  },
  {
    name: "Yahoo!広告",
    pattern: "Yahoo!広告",
    matchType: "contains",
    accountCode: "521",
    accountName: "広告宣伝費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "Yahoo!プロモーション広告",
  },
  {
    name: "LINE広告",
    pattern: "LINE広告",
    matchType: "contains",
    accountCode: "521",
    accountName: "広告宣伝費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "LINE Ads Platform",
  },
  {
    name: "Twitter/X広告",
    pattern: "Twitter広告|X広告",
    matchType: "regex",
    accountCode: "521",
    accountName: "広告宣伝費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "X（旧Twitter）広告",
  },
  {
    name: "TikTok広告",
    pattern: "TikTok広告",
    matchType: "contains",
    accountCode: "521",
    accountName: "広告宣伝費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "TikTok for Business",
  },
  {
    name: "Microsoft広告",
    pattern: "Microsoft広告",
    matchType: "contains",
    accountCode: "521",
    accountName: "広告宣伝費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "Bing Ads",
  },
  {
    name: "SmartNews Ads",
    pattern: "SmartNews",
    matchType: "contains",
    accountCode: "521",
    accountName: "広告宣伝費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    note: "SmartNews広告",
  },

  // ── PR ──
  {
    name: "PR TIMES",
    pattern: "PR TIMES",
    matchType: "contains",
    accountCode: "521",
    accountName: "広告宣伝費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "プレスリリース配信",
  },
  {
    name: "@Press",
    pattern: "@Press",
    matchType: "contains",
    accountCode: "521",
    accountName: "広告宣伝費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "プレスリリース配信",
  },

  // ── SEO / マーケティングツール ──
  {
    name: "Ahrefs",
    pattern: "Ahrefs",
    matchType: "contains",
    accountCode: "521",
    accountName: "広告宣伝費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "SEO分析ツール",
  },
  {
    name: "SEMrush",
    pattern: "SEMrush",
    matchType: "contains",
    accountCode: "521",
    accountName: "広告宣伝費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "SEO/マーケティングツール",
  },
  {
    name: "Moz",
    pattern: "Moz",
    matchType: "contains",
    accountCode: "521",
    accountName: "広告宣伝費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.8,
    note: "Moz Pro SEOツール",
  },
  {
    name: "GRC",
    pattern: "GRC",
    matchType: "contains",
    accountCode: "521",
    accountName: "広告宣伝費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.8,
    note: "検索順位チェックツール",
  },
  {
    name: "ラッコキーワード",
    pattern: "ラッコキーワード",
    matchType: "contains",
    accountCode: "521",
    accountName: "広告宣伝費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "キーワード調査ツール",
  },
  {
    name: "SocialDog",
    pattern: "SocialDog",
    matchType: "contains",
    accountCode: "521",
    accountName: "広告宣伝費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "SNS運用ツール",
  },
  {
    name: "Buffer",
    pattern: "Buffer",
    matchType: "contains",
    accountCode: "521",
    accountName: "広告宣伝費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.85,
    note: "SNS投稿管理ツール",
  },
  {
    name: "Mailchimp",
    pattern: "Mailchimp",
    matchType: "contains",
    accountCode: "521",
    accountName: "広告宣伝費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    note: "メールマーケティング",
  },
  {
    name: "SendGrid",
    pattern: "SendGrid",
    matchType: "contains",
    accountCode: "521",
    accountName: "広告宣伝費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    note: "メール配信サービス（Twilio系）",
  },

  // ── 印刷 ──
  {
    name: "ラクスル",
    pattern: "ラクスル",
    matchType: "contains",
    accountCode: "521",
    accountName: "広告宣伝費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    note: "ネット印刷",
  },
  {
    name: "プリントパック",
    pattern: "プリントパック",
    matchType: "contains",
    accountCode: "521",
    accountName: "広告宣伝費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    note: "ネット印刷",
  },
  {
    name: "グラフィック",
    pattern: "グラフィック",
    matchType: "contains",
    accountCode: "521",
    accountName: "広告宣伝費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.7,
    note: "印刷通販グラフィック — 一般的な単語のため confidence 低め",
  },
];
