// This file is part of kanjokamoku — MIT License
// https://github.com/tsubasagit/kanjokamoku

import type { ClassificationRule } from "./types";

/**
 * 保険料 → 保険料(525)
 * 損害保険・生命保険・自動車保険を分類する。
 * 保険は非課税取引。
 * counterAccount: 普通預金(102) — 口座振替が一般的
 */
export const INSURANCE_RULES: ClassificationRule[] = [
  // ── 損害保険 ──
  {
    name: "東京海上日動",
    pattern: "東京海上日動",
    matchType: "contains",
    accountCode: "525",
    accountName: "保険料",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    note: "東京海上日動火災保険 — 非課税取引",
    consumptionTaxClass: "非課税仕入",
  },
  {
    name: "三井住友海上",
    pattern: "三井住友海上",
    matchType: "contains",
    accountCode: "525",
    accountName: "保険料",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    note: "非課税取引",
    consumptionTaxClass: "非課税仕入",
  },
  {
    name: "損保ジャパン",
    pattern: "損保ジャパン",
    matchType: "contains",
    accountCode: "525",
    accountName: "保険料",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    note: "非課税取引",
    consumptionTaxClass: "非課税仕入",
  },
  {
    name: "あいおいニッセイ同和",
    pattern: "あいおいニッセイ",
    matchType: "contains",
    accountCode: "525",
    accountName: "保険料",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    note: "あいおいニッセイ同和損害保険 — 非課税取引",
    consumptionTaxClass: "非課税仕入",
  },
  {
    name: "AIG損保",
    pattern: "AIG損保",
    matchType: "contains",
    accountCode: "525",
    accountName: "保険料",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    note: "AIG損害保険 — 非課税取引",
    consumptionTaxClass: "非課税仕入",
  },

  // ── 生命保険 ──
  {
    name: "日本生命",
    pattern: "日本生命",
    matchType: "contains",
    accountCode: "525",
    accountName: "保険料",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    note: "非課税取引",
    consumptionTaxClass: "非課税仕入",
  },
  {
    name: "第一生命",
    pattern: "第一生命",
    matchType: "contains",
    accountCode: "525",
    accountName: "保険料",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    note: "非課税取引",
    consumptionTaxClass: "非課税仕入",
  },
  {
    name: "明治安田生命",
    pattern: "明治安田生命",
    matchType: "contains",
    accountCode: "525",
    accountName: "保険料",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    note: "非課税取引",
    consumptionTaxClass: "非課税仕入",
  },
  {
    name: "住友生命",
    pattern: "住友生命",
    matchType: "contains",
    accountCode: "525",
    accountName: "保険料",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    note: "非課税取引",
    consumptionTaxClass: "非課税仕入",
  },
  {
    name: "メットライフ生命",
    pattern: "メットライフ",
    matchType: "contains",
    accountCode: "525",
    accountName: "保険料",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    note: "MetLife — 非課税取引",
    consumptionTaxClass: "非課税仕入",
  },
  {
    name: "アフラック",
    pattern: "アフラック",
    matchType: "contains",
    accountCode: "525",
    accountName: "保険料",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    note: "Aflac — 非課税取引",
    consumptionTaxClass: "非課税仕入",
  },
  {
    name: "オリックス生命",
    pattern: "オリックス生命",
    matchType: "contains",
    accountCode: "525",
    accountName: "保険料",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    note: "非課税取引",
    consumptionTaxClass: "非課税仕入",
  },

  // ── 自動車保険（ダイレクト系） ──
  {
    name: "ソニー損保",
    pattern: "ソニー損保",
    matchType: "contains",
    accountCode: "525",
    accountName: "保険料",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    note: "ソニー損害保険 — 非課税取引",
    consumptionTaxClass: "非課税仕入",
  },
  {
    name: "イーデザイン損保",
    pattern: "イーデザイン損保",
    matchType: "contains",
    accountCode: "525",
    accountName: "保険料",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    note: "東京海上グループ — 非課税取引",
    consumptionTaxClass: "非課税仕入",
  },
  {
    name: "チューリッヒ保険",
    pattern: "チューリッヒ",
    matchType: "contains",
    accountCode: "525",
    accountName: "保険料",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    note: "Zurich Insurance — 非課税取引",
    consumptionTaxClass: "非課税仕入",
  },
  {
    name: "アクサダイレクト",
    pattern: "アクサダイレクト",
    matchType: "contains",
    accountCode: "525",
    accountName: "保険料",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    note: "AXA — 非課税取引",
    consumptionTaxClass: "非課税仕入",
  },
  {
    name: "SBI損保",
    pattern: "SBI損保",
    matchType: "contains",
    accountCode: "525",
    accountName: "保険料",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    note: "SBI損害保険 — 非課税取引",
    consumptionTaxClass: "非課税仕入",
  },
];
