// This file is part of kanjokamoku — MIT License
// https://github.com/tsubasagit/kanjokamoku

import type { ClassificationRule } from "./types";

/**
 * 学習・研修関連費用
 * 書籍・新聞 → 新聞図書費(516)
 * オンライン学習・資格取得 → 研修費(527)
 * counterAccount: クレジットカード(203)
 */
export const LEARNING_RULES: ClassificationRule[] = [
  // ── 書店 → 新聞図書費(516) ──
  {
    name: "紀伊國屋書店",
    pattern: "紀伊國屋",
    matchType: "contains",
    accountCode: "516",
    accountName: "新聞図書費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
  },
  {
    name: "ジュンク堂書店",
    pattern: "ジュンク堂",
    matchType: "contains",
    accountCode: "516",
    accountName: "新聞図書費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
  },
  {
    name: "三省堂書店",
    pattern: "三省堂",
    matchType: "contains",
    accountCode: "516",
    accountName: "新聞図書費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.85,
    note: "辞書出版社と区別が必要な場合あり",
  },
  {
    name: "TSUTAYA",
    pattern: "TSUTAYA",
    matchType: "contains",
    accountCode: "516",
    accountName: "新聞図書費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.7,
    note: "書籍以外（レンタル等）の可能性あり",
  },
  {
    name: "honto",
    pattern: "honto",
    matchType: "contains",
    accountCode: "516",
    accountName: "新聞図書費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    note: "丸善ジュンク堂系オンライン書店",
  },
  {
    name: "啓文堂書店",
    pattern: "啓文堂",
    matchType: "contains",
    accountCode: "516",
    accountName: "新聞図書費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
  },
  {
    name: "ブックオフ",
    pattern: "ブックオフ",
    matchType: "contains",
    accountCode: "516",
    accountName: "新聞図書費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.8,
    note: "書籍以外の中古品も取り扱い",
  },
  {
    name: "Kindle",
    pattern: "Kindle",
    matchType: "contains",
    accountCode: "516",
    accountName: "新聞図書費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    note: "Amazon Kindle電子書籍",
  },
  {
    name: "楽天ブックス",
    pattern: "楽天ブックス",
    matchType: "contains",
    accountCode: "516",
    accountName: "新聞図書費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
  },

  // ── 新聞 → 新聞図書費(516) ──
  {
    name: "日本経済新聞",
    pattern: "日本経済新聞",
    matchType: "contains",
    accountCode: "516",
    accountName: "新聞図書費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "朝日新聞",
    pattern: "朝日新聞",
    matchType: "contains",
    accountCode: "516",
    accountName: "新聞図書費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "読売新聞",
    pattern: "読売新聞",
    matchType: "contains",
    accountCode: "516",
    accountName: "新聞図書費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "毎日新聞",
    pattern: "毎日新聞",
    matchType: "contains",
    accountCode: "516",
    accountName: "新聞図書費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "日経電子版",
    pattern: "日経電子版",
    matchType: "contains",
    accountCode: "516",
    accountName: "新聞図書費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "日本経済新聞デジタル版",
  },
  {
    name: "NewsPicks",
    pattern: "NewsPicks",
    matchType: "contains",
    accountCode: "516",
    accountName: "新聞図書費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    note: "経済ニュースメディア",
  },

  // ── オンライン学習 → 研修費(527) ──
  {
    name: "Udemy",
    pattern: "Udemy",
    matchType: "contains",
    accountCode: "527",
    accountName: "研修費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "Coursera",
    pattern: "Coursera",
    matchType: "contains",
    accountCode: "527",
    accountName: "研修費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "Progate",
    pattern: "Progate",
    matchType: "contains",
    accountCode: "527",
    accountName: "研修費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "プログラミング学習サービス",
  },
  {
    name: "TechAcademy",
    pattern: "TechAcademy",
    matchType: "contains",
    accountCode: "527",
    accountName: "研修費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "Schoo",
    pattern: "Schoo",
    matchType: "contains",
    accountCode: "527",
    accountName: "研修費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
  },
  {
    name: "ストアカ",
    pattern: "ストアカ",
    matchType: "contains",
    accountCode: "527",
    accountName: "研修費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    note: "ストリートアカデミー",
  },
  {
    name: "LinkedIn Learning",
    pattern: "LinkedIn Learning",
    matchType: "contains",
    accountCode: "527",
    accountName: "研修費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "Pluralsight",
    pattern: "Pluralsight",
    matchType: "contains",
    accountCode: "527",
    accountName: "研修費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },

  // ── 資格取得 → 研修費(527) ──
  {
    name: "資格の大原",
    pattern: "大原",
    matchType: "contains",
    accountCode: "527",
    accountName: "研修費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.8,
    note: "資格の大原（大原学園）",
  },
  {
    name: "TAC",
    pattern: "TAC",
    matchType: "contains",
    accountCode: "527",
    accountName: "研修費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.8,
    note: "TAC株式会社 資格スクール",
  },
  {
    name: "LEC東京リーガルマインド",
    pattern: "LEC",
    matchType: "contains",
    accountCode: "527",
    accountName: "研修費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.8,
    note: "LEC東京リーガルマインド",
  },
  {
    name: "ユーキャン",
    pattern: "ユーキャン",
    matchType: "contains",
    accountCode: "527",
    accountName: "研修費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    note: "通信教育・資格講座",
  },
];
