// This file is part of kanjokamoku — MIT License
// https://github.com/tsubasagit/kanjokamoku

import type { ClassificationRule } from "./types";

/**
 * 士業・専門家・外注費用
 * 法律・会計・社労士 → 支払手数料(517)
 * コンサルティング・制作外注 → 外注費(518)
 * counterAccount: 普通預金(102)
 */
export const PROFESSIONAL_RULES: ClassificationRule[] = [
  // ── 法律系 → 支払手数料(517) ──
  {
    name: "弁護士",
    pattern: "弁護士",
    matchType: "contains",
    accountCode: "517",
    accountName: "支払手数料",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.9,
    note: "源泉徴収の対象",
  },
  {
    name: "司法書士",
    pattern: "司法書士",
    matchType: "contains",
    accountCode: "517",
    accountName: "支払手数料",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.9,
    note: "登記手続き等 — 源泉徴収の対象",
  },
  {
    name: "行政書士",
    pattern: "行政書士",
    matchType: "contains",
    accountCode: "517",
    accountName: "支払手数料",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.9,
  },
  {
    name: "弁理士",
    pattern: "弁理士",
    matchType: "contains",
    accountCode: "517",
    accountName: "支払手数料",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.9,
    note: "特許・商標出願 — 源泉徴収の対象",
  },
  {
    name: "法律事務所",
    pattern: "法律事務所",
    matchType: "contains",
    accountCode: "517",
    accountName: "支払手数料",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
  },
  {
    name: "法務事務所",
    pattern: "法務事務所",
    matchType: "contains",
    accountCode: "517",
    accountName: "支払手数料",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
  },

  // ── 会計系 → 支払手数料(517) ──
  {
    name: "税理士",
    pattern: "税理士",
    matchType: "contains",
    accountCode: "517",
    accountName: "支払手数料",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    note: "源泉徴収の対象",
  },
  {
    name: "公認会計士",
    pattern: "公認会計士",
    matchType: "contains",
    accountCode: "517",
    accountName: "支払手数料",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    note: "源泉徴収の対象",
  },
  {
    name: "税理士事務所",
    pattern: "税理士事務所",
    matchType: "contains",
    accountCode: "517",
    accountName: "支払手数料",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
  },
  {
    name: "会計事務所",
    pattern: "会計事務所",
    matchType: "contains",
    accountCode: "517",
    accountName: "支払手数料",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
  },
  {
    name: "記帳代行",
    pattern: "記帳代行",
    matchType: "contains",
    accountCode: "517",
    accountName: "支払手数料",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.9,
  },

  // ── 労務系 → 支払手数料(517) ──
  {
    name: "社会保険労務士",
    pattern: "社会保険労務士",
    matchType: "contains",
    accountCode: "517",
    accountName: "支払手数料",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    note: "源泉徴収の対象",
  },
  {
    name: "社労士",
    pattern: "社労士",
    matchType: "contains",
    accountCode: "517",
    accountName: "支払手数料",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.9,
    note: "社会保険労務士の略称",
  },

  // ── コンサルティング → 外注費(518) ──
  {
    name: "コンサルティング",
    pattern: "コンサルティング",
    matchType: "contains",
    accountCode: "518",
    accountName: "外注費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.85,
  },
  {
    name: "コンサルタント",
    pattern: "コンサルタント",
    matchType: "contains",
    accountCode: "518",
    accountName: "外注費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.85,
  },
  {
    name: "アドバイザリー",
    pattern: "アドバイザリー",
    matchType: "contains",
    accountCode: "518",
    accountName: "外注費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.85,
  },

  // ── 制作外注 → 外注費(518) ──
  {
    name: "デザイナー",
    pattern: "デザイナー",
    matchType: "contains",
    accountCode: "518",
    accountName: "外注費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.8,
    note: "フリーランスデザイナーへの外注",
  },
  {
    name: "イラストレーター",
    pattern: "イラストレーター",
    matchType: "contains",
    accountCode: "518",
    accountName: "外注費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.8,
    note: "フリーランスイラストレーターへの外注",
  },
  {
    name: "カメラマン",
    pattern: "カメラマン",
    matchType: "contains",
    accountCode: "518",
    accountName: "外注費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.85,
    note: "撮影外注",
  },
  {
    name: "ライター",
    pattern: "ライター",
    matchType: "contains",
    accountCode: "518",
    accountName: "外注費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.8,
    note: "記事執筆外注",
  },
  {
    name: "翻訳",
    pattern: "翻訳",
    matchType: "contains",
    accountCode: "518",
    accountName: "外注費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.85,
  },
  {
    name: "Web制作",
    pattern: "Web制作",
    matchType: "contains",
    accountCode: "518",
    accountName: "外注費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.9,
  },
  {
    name: "システム開発",
    pattern: "システム開発",
    matchType: "contains",
    accountCode: "518",
    accountName: "外注費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.9,
  },
];
