// This file is part of kanjokamoku — MIT License
// https://github.com/tsubasagit/kanjokamoku

import type { ClassificationRule } from "./types";

/**
 * SaaS・クラウドサービス → 通信費(512)
 * counterAccount: クレジットカード(203)
 */
export const SAAS_RULES: ClassificationRule[] = [
  // ── Cloud ──
  {
    name: "AWS",
    pattern: "AWS",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "Amazon Web Services",
  },
  {
    name: "Amazon Web Services",
    pattern: "Amazon Web Services",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.97,
  },
  {
    name: "Google Cloud",
    pattern: "Google Cloud",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "Google Workspace",
    pattern: "Google Workspace",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "旧G Suite",
  },
  {
    name: "Azure",
    pattern: "Azure",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    note: "Microsoft Azure",
  },
  {
    name: "Microsoft 365",
    pattern: "Microsoft 365",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "旧Office 365",
  },
  {
    name: "Oracle Cloud",
    pattern: "Oracle Cloud",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "SAP Cloud",
    pattern: "SAP Cloud",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },

  // ── Hosting ──
  {
    name: "Vercel",
    pattern: "Vercel",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "Firebase",
    pattern: "Firebase",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    note: "Google Firebase",
  },
  {
    name: "Heroku",
    pattern: "Heroku",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "Netlify",
    pattern: "Netlify",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "Railway",
    pattern: "Railway",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.85,
    note: "Railway.app",
  },
  {
    name: "Render",
    pattern: "Render",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.8,
    note: "render.com — 一般的な単語のため confidence 低め",
  },
  {
    name: "Fly.io",
    pattern: "Fly.io",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "Supabase",
    pattern: "Supabase",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "PlanetScale",
    pattern: "PlanetScale",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "Neon",
    pattern: "Neon",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.75,
    note: "Neon Database — 一般的な単語のため confidence 低め",
  },

  // ── Communication ──
  {
    name: "Slack",
    pattern: "Slack",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
  },
  {
    name: "Zoom",
    pattern: "Zoom",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    note: "Zoom Video Communications",
  },
  {
    name: "Microsoft Teams",
    pattern: "Microsoft Teams",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "Google Meet",
    pattern: "Google Meet",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "Discord",
    pattern: "Discord",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    note: "Discord Nitro等の有料プラン",
  },

  // ── Productivity ──
  {
    name: "Notion",
    pattern: "Notion",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
  },
  {
    name: "Obsidian",
    pattern: "Obsidian",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.85,
    note: "Obsidian Sync/Publish等の有料機能",
  },
  {
    name: "Evernote",
    pattern: "Evernote",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "Dropbox",
    pattern: "Dropbox",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "Box",
    pattern: "Box",
    matchType: "exact",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.8,
    note: "Box Inc. — 短い名称のため exact match",
  },
  {
    name: "Google Drive/One",
    pattern: "Google (Drive|One)",
    matchType: "regex",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "Google Drive / Google One ストレージ",
  },

  // ── PM ──
  {
    name: "Asana",
    pattern: "Asana",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
  },
  {
    name: "JIRA",
    pattern: "JIRA",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "Atlassian JIRA",
  },
  {
    name: "Trello",
    pattern: "Trello",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "Monday.com",
    pattern: "Monday.com",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "ClickUp",
    pattern: "ClickUp",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "Backlog",
    pattern: "Backlog",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.85,
    note: "Nulab Backlog",
  },
  {
    name: "Redmine Cloud",
    pattern: "Redmine",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.85,
    note: "Redmine クラウド版",
  },
  {
    name: "Linear",
    pattern: "Linear",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.8,
    note: "Linear.app — 一般的な単語のため confidence 低め",
  },

  // ── CRM ──
  {
    name: "Salesforce",
    pattern: "Salesforce",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "HubSpot",
    pattern: "HubSpot",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "Zoho",
    pattern: "Zoho",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
  },
  {
    name: "kintone",
    pattern: "kintone",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "サイボウズ kintone",
  },

  // ── Design ──
  {
    name: "Figma",
    pattern: "Figma",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "Adobe Creative Cloud",
    pattern: "Adobe",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    note: "Adobe Creative Cloud サブスクリプション",
  },
  {
    name: "Canva",
    pattern: "Canva",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "Miro",
    pattern: "Miro",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
  },
  {
    name: "Sketch",
    pattern: "Sketch",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.8,
    note: "Sketch.com — 一般的な単語のため confidence 低め",
  },

  // ── HR ──
  {
    name: "SmartHR",
    pattern: "SmartHR",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "freee人事労務",
    pattern: "freee人事",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "KING OF TIME",
    pattern: "KING OF TIME",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "勤怠管理SaaS",
  },
  {
    name: "ジョブカン",
    pattern: "ジョブカン",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },

  // ── No-code ──
  {
    name: "Zapier",
    pattern: "Zapier",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "Make(Integromat)",
    pattern: "Make|Integromat",
    matchType: "regex",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.8,
    note: "旧Integromat — Make は一般的な単語のため confidence 低め",
  },
  {
    name: "Airtable",
    pattern: "Airtable",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "Webflow",
    pattern: "Webflow",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },

  // ── DevOps ──
  {
    name: "GitHub",
    pattern: "GitHub",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "GitLab",
    pattern: "GitLab",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "Bitbucket",
    pattern: "Bitbucket",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "Atlassian Bitbucket",
  },
  {
    name: "CircleCI",
    pattern: "CircleCI",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "Docker Hub",
    pattern: "Docker",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    note: "Docker Hub / Docker Desktop サブスクリプション",
  },

  // ── Monitoring ──
  {
    name: "Datadog",
    pattern: "Datadog",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "New Relic",
    pattern: "New Relic",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "Sentry",
    pattern: "Sentry",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
  },
  {
    name: "PagerDuty",
    pattern: "PagerDuty",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },

  // ── AI ──
  {
    name: "OpenAI",
    pattern: "OpenAI",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "ChatGPT / GPT API",
  },
  {
    name: "Anthropic",
    pattern: "Anthropic",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "Claude API",
  },
  {
    name: "Midjourney",
    pattern: "Midjourney",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "Stability AI",
    pattern: "Stability",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.85,
    note: "Stable Diffusion API 等",
  },

  // ── Japan hosting ──
  {
    name: "さくらインターネット",
    pattern: "さくらインターネット",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "エックスサーバー",
    pattern: "エックスサーバー",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "ロリポップ",
    pattern: "ロリポップ",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "GMOペパボ ロリポップ!",
  },
  {
    name: "ConoHa",
    pattern: "ConoHa",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "GMOインターネット ConoHa",
  },
];
