// This file is part of kanjokamoku — MIT License
// https://github.com/tsubasagit/kanjokamoku

import type { ClassificationRule } from "./types";

/**
 * 荷造運賃 → 荷造運賃(533)
 * 国内外の配送・郵便サービスを分類する。
 * counterAccount: 現金(101) or クレジットカード(203)
 */
export const SHIPPING_RULES: ClassificationRule[] = [
  // ── 国内配送 ──
  {
    name: "日本郵便",
    pattern: "日本郵便",
    matchType: "contains",
    accountCode: "533",
    accountName: "荷造運賃",
    counterAccountCode: "101",
    counterAccountName: "現金",
    confidence: 0.9,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "ヤマト運輸",
    pattern: "ヤマト運輸",
    matchType: "contains",
    accountCode: "533",
    accountName: "荷造運賃",
    counterAccountCode: "101",
    counterAccountName: "現金",
    confidence: 0.95,
    note: "クロネコヤマト",
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "佐川急便",
    pattern: "佐川急便",
    matchType: "contains",
    accountCode: "533",
    accountName: "荷造運賃",
    counterAccountCode: "101",
    counterAccountName: "現金",
    confidence: 0.95,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "西濃運輸",
    pattern: "西濃運輸",
    matchType: "contains",
    accountCode: "533",
    accountName: "荷造運賃",
    counterAccountCode: "101",
    counterAccountName: "現金",
    confidence: 0.95,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "福山通運",
    pattern: "福山通運",
    matchType: "contains",
    accountCode: "533",
    accountName: "荷造運賃",
    counterAccountCode: "101",
    counterAccountName: "現金",
    confidence: 0.95,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "日本通運",
    pattern: "日本通運",
    matchType: "contains",
    accountCode: "533",
    accountName: "荷造運賃",
    counterAccountCode: "101",
    counterAccountName: "現金",
    confidence: 0.9,
    note: "NX日本通運",
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "クリックポスト",
    pattern: "クリックポスト",
    matchType: "contains",
    accountCode: "533",
    accountName: "荷造運賃",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "日本郵便 クリックポスト",
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "レターパック",
    pattern: "レターパック",
    matchType: "contains",
    accountCode: "533",
    accountName: "荷造運賃",
    counterAccountCode: "101",
    counterAccountName: "現金",
    confidence: 0.95,
    note: "日本郵便 レターパック",
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "ゆうパック",
    pattern: "ゆうパック",
    matchType: "contains",
    accountCode: "533",
    accountName: "荷造運賃",
    counterAccountCode: "101",
    counterAccountName: "現金",
    confidence: 0.95,
    note: "日本郵便 ゆうパック",
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "ネコポス",
    pattern: "ネコポス",
    matchType: "contains",
    accountCode: "533",
    accountName: "荷造運賃",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "ヤマト運輸 ネコポス",
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },

  // ── 国際配送 ──
  {
    name: "DHL",
    pattern: "DHL",
    matchType: "contains",
    accountCode: "533",
    accountName: "荷造運賃",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    note: "DHL Express 国際宅配便",
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
    taxNotes: ["国際輸送の場合は輸出免税の可能性あり。国内配送部分は課税仕入10%"],
  },
  {
    name: "FedEx",
    pattern: "FedEx",
    matchType: "contains",
    accountCode: "533",
    accountName: "荷造運賃",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
    taxNotes: ["国際輸送の場合は輸出免税の可能性あり。国内配送部分は課税仕入10%"],
  },
  {
    name: "UPS",
    pattern: "UPS",
    matchType: "contains",
    accountCode: "533",
    accountName: "荷造運賃",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.85,
    note: "United Parcel Service",
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
    taxNotes: ["国際輸送の場合は輸出免税の可能性あり。国内配送部分は課税仕入10%"],
  },
  {
    name: "EMS",
    pattern: "EMS",
    matchType: "contains",
    accountCode: "533",
    accountName: "荷造運賃",
    counterAccountCode: "101",
    counterAccountName: "現金",
    confidence: 0.8,
    note: "国際スピード郵便（日本郵便）",
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
    taxNotes: ["国際輸送の場合は輸出免税の可能性あり。国内配送部分は課税仕入10%"],
  },
];
