// This file is part of kanjokamoku — MIT License
// https://github.com/tsubasagit/kanjokamoku

import type { ClassificationRule } from "./types";

/**
 * サブスクリプションサービス
 * 動画・音楽・ストレージ → 通信費(512)
 * ニュース系 → 新聞図書費(516)
 * counterAccount: クレジットカード(203)
 */
export const SUBSCRIPTION_RULES: ClassificationRule[] = [
  // ── 動画配信 → 通信費(512) ──
  {
    name: "Netflix",
    pattern: "Netflix",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "業務利用の場合のみ経費計上可",
  },
  {
    name: "Amazon Prime",
    pattern: "Amazon Prime|Amazonプライム",
    matchType: "regex",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.85,
    note: "配送特典含むため按分が必要な場合あり",
  },
  {
    name: "Disney+",
    pattern: "Disney\\+|ディズニープラス",
    matchType: "regex",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "業務利用の場合のみ経費計上可",
  },
  {
    name: "Hulu",
    pattern: "Hulu",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "業務利用の場合のみ経費計上可",
  },
  {
    name: "U-NEXT",
    pattern: "U-NEXT",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "業務利用の場合のみ経費計上可",
  },
  {
    name: "DAZN",
    pattern: "DAZN",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "スポーツ配信 — 業務利用の場合のみ経費計上可",
  },
  {
    name: "ABEMA",
    pattern: "ABEMA",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    note: "ABEMAプレミアム",
  },
  {
    name: "WOWOW",
    pattern: "WOWOW",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "dTV",
    pattern: "dTV",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    note: "NTTドコモ Lemino（旧dTV）",
  },
  {
    name: "Paravi",
    pattern: "Paravi",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "U-NEXTに統合済み",
  },
  {
    name: "Apple TV+",
    pattern: "Apple TV",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    note: "Apple TV+ サブスクリプション",
  },

  // ── 音楽配信 → 通信費(512) ──
  {
    name: "Spotify",
    pattern: "Spotify",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "Apple Music",
    pattern: "Apple Music",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "Amazon Music",
    pattern: "Amazon Music",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "YouTube Music",
    pattern: "YouTube Music",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "LINE MUSIC",
    pattern: "LINE MUSIC",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
  },
  {
    name: "AWA",
    pattern: "AWA",
    matchType: "exact",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.8,
    note: "AWA音楽配信 — 短い名称のため exact match",
  },

  // ── ストレージ → 通信費(512) ──
  {
    name: "iCloud",
    pattern: "iCloud",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    note: "iCloud+ ストレージプラン",
  },
  {
    name: "Google One",
    pattern: "Google One",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "Google Oneストレージプラン",
  },

  // ── ニュース系 → 新聞図書費(516) ──
  {
    name: "NewsPicks（定期購読）",
    pattern: "NewsPicks",
    matchType: "contains",
    accountCode: "516",
    accountName: "新聞図書費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    note: "経済ニュースメディア定期購読",
  },
  {
    name: "日経電子版（定期購読）",
    pattern: "日経電子版",
    matchType: "contains",
    accountCode: "516",
    accountName: "新聞図書費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "日本経済新聞デジタル版定期購読",
  },
];
