// This file is part of kanjokamoku — MIT License
// https://github.com/tsubasagit/kanjokamoku

import type { ClassificationRule } from "./types";

/**
 * 租税公課 → 租税公課(524)
 * 各種税金・印紙税等を分類する。
 * 全て不課税（消費税対象外）。
 * counterAccount: 現金(101) or 普通預金(102)
 */
export const TAX_FEE_RULES: ClassificationRule[] = [
  {
    name: "印紙税",
    pattern: "印紙税",
    matchType: "contains",
    accountCode: "524",
    accountName: "租税公課",
    counterAccountCode: "101",
    counterAccountName: "現金",
    confidence: 0.95,
    note: "不課税取引",
  },
  {
    name: "収入印紙",
    pattern: "収入印紙",
    matchType: "contains",
    accountCode: "524",
    accountName: "租税公課",
    counterAccountCode: "101",
    counterAccountName: "現金",
    confidence: 0.95,
    note: "不課税取引",
  },
  {
    name: "登録免許税",
    pattern: "登録免許税",
    matchType: "contains",
    accountCode: "524",
    accountName: "租税公課",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    note: "法人登記・不動産登記等 — 不課税取引",
  },
  {
    name: "自動車税",
    pattern: "自動車税",
    matchType: "contains",
    accountCode: "524",
    accountName: "租税公課",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    note: "不課税取引",
  },
  {
    name: "自動車重量税",
    pattern: "自動車重量税",
    matchType: "contains",
    accountCode: "524",
    accountName: "租税公課",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    note: "不課税取引",
  },
  {
    name: "固定資産税",
    pattern: "固定資産税",
    matchType: "contains",
    accountCode: "524",
    accountName: "租税公課",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    note: "不課税取引",
  },
  {
    name: "不動産取得税",
    pattern: "不動産取得税",
    matchType: "contains",
    accountCode: "524",
    accountName: "租税公課",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    note: "不課税取引",
  },
  {
    name: "事業所税",
    pattern: "事業所税",
    matchType: "contains",
    accountCode: "524",
    accountName: "租税公課",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    note: "不課税取引",
  },
  {
    name: "個人事業税",
    pattern: "個人事業税",
    matchType: "contains",
    accountCode: "524",
    accountName: "租税公課",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    note: "不課税取引",
  },
  {
    name: "法人事業税",
    pattern: "法人事業税",
    matchType: "contains",
    accountCode: "524",
    accountName: "租税公課",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    note: "不課税取引",
  },
  {
    name: "法人住民税",
    pattern: "法人住民税",
    matchType: "contains",
    accountCode: "524",
    accountName: "租税公課",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    note: "不課税取引",
  },
  {
    name: "償却資産税",
    pattern: "償却資産税",
    matchType: "contains",
    accountCode: "524",
    accountName: "租税公課",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    note: "固定資産税（償却資産） — 不課税取引",
  },
];
