// This file is part of kanjokamoku — MIT License
// https://github.com/tsubasagit/kanjokamoku

import type { ClassificationRule } from "./types";

/**
 * 通信キャリア・ISP → 通信費(512)
 * Major carriers / ISP: counterAccount = 普通預金(102) — 口座振替が一般的
 * MVNO: counterAccount = クレジットカード(203) — クレカ払いが主流
 */
export const TELECOM_RULES: ClassificationRule[] = [
  // ── Major carriers（口座振替） ──
  {
    name: "NTTドコモ",
    pattern: "NTTドコモ|ドコモ",
    matchType: "regex",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "KDDI/au",
    pattern: "KDDI|\\bau\\b",
    matchType: "regex",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.9,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "ソフトバンク",
    pattern: "ソフトバンク",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.9,
    note: "SoftBank モバイル / 光",
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },

  // ── Sub-brands（口座振替） ──
  {
    name: "UQモバイル",
    pattern: "UQモバイル|UQ mobile",
    matchType: "regex",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    note: "KDDI サブブランド",
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "Y!mobile",
    pattern: "Y!mobile|ワイモバイル",
    matchType: "regex",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    note: "ソフトバンク サブブランド",
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "povo",
    pattern: "povo",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    note: "KDDI オンライン専用プラン",
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "LINEMO",
    pattern: "LINEMO",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "ソフトバンク オンライン専用プラン",
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "ahamo",
    pattern: "ahamo",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "ドコモ オンライン専用プラン",
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },

  // ── MVNO（クレジットカード） ──
  {
    name: "楽天モバイル",
    pattern: "楽天モバイル",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "IIJmio",
    pattern: "IIJmio|IIJ",
    matchType: "regex",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "mineo",
    pattern: "mineo",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "オプテージ mineo",
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "OCNモバイルONE",
    pattern: "OCNモバイル|OCN モバイル",
    matchType: "regex",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "BIGLOBEモバイル",
    pattern: "BIGLOBEモバイル|BIGLOBE",
    matchType: "regex",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "nuroモバイル",
    pattern: "nuroモバイル",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "イオンモバイル",
    pattern: "イオンモバイル",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },

  // ── ISP（口座振替） ──
  {
    name: "NTT東日本",
    pattern: "NTT東日本",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    note: "フレッツ光等の固定回線",
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "NTT西日本",
    pattern: "NTT西日本",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    note: "フレッツ光等の固定回線",
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "NURO光",
    pattern: "NURO光|NURO 光",
    matchType: "regex",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    note: "ソニーネットワークコミュニケーションズ",
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "auひかり",
    pattern: "auひかり|au ひかり",
    matchType: "regex",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "So-net",
    pattern: "So-net",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.9,
    note: "ソニーネットワークコミュニケーションズ",
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "フレッツ光",
    pattern: "フレッツ光|フレッツ 光",
    matchType: "regex",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    note: "NTT東西のフレッツ光サービス",
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
];
