// This file is part of kanjokamoku — MIT License
// https://github.com/tsubasagit/kanjokamoku

import type { ClassificationRule } from "./types";

/**
 * 交通 → 旅費交通費(511)
 * counterAccount は支払い方法に応じて振り分け:
 *   現金(101) — タクシー・バス等の現金払い
 *   クレジットカード(203) — 航空券・レンタカー・ETC等
 */
export const TRANSPORT_RULES: ClassificationRule[] = [
  // ── JR ──
  {
    name: "JR",
    pattern: "\\bJR\\b",
    matchType: "regex",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "101",
    counterAccountName: "現金",
    confidence: 0.85,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
    note: "JR各社共通パターン",
  },
  {
    name: "JR東日本",
    pattern: "JR東日本",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "101",
    counterAccountName: "現金",
    confidence: 0.95,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "JR西日本",
    pattern: "JR西日本",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "101",
    counterAccountName: "現金",
    confidence: 0.95,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "JR東海",
    pattern: "JR東海",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "101",
    counterAccountName: "現金",
    confidence: 0.95,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "新幹線",
    pattern: "新幹線",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
    note: "EX-IC等のクレカ決済が一般的",
  },

  // ── Private railways ──
  {
    name: "東急",
    pattern: "東急",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "101",
    counterAccountName: "現金",
    confidence: 0.85,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "小田急",
    pattern: "小田急",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "101",
    counterAccountName: "現金",
    confidence: 0.9,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "京王",
    pattern: "京王",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "101",
    counterAccountName: "現金",
    confidence: 0.85,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "西武",
    pattern: "西武",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "101",
    counterAccountName: "現金",
    confidence: 0.8,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
    note: "西武鉄道 — 西武百貨店等と区別が必要",
  },
  {
    name: "東武",
    pattern: "東武",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "101",
    counterAccountName: "現金",
    confidence: 0.8,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
    note: "東武鉄道 — 東武百貨店等と区別が必要",
  },
  {
    name: "京急",
    pattern: "京急",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "101",
    counterAccountName: "現金",
    confidence: 0.9,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "相鉄",
    pattern: "相鉄",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "101",
    counterAccountName: "現金",
    confidence: 0.9,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "京成",
    pattern: "京成",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "101",
    counterAccountName: "現金",
    confidence: 0.9,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "阪急",
    pattern: "阪急",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "101",
    counterAccountName: "現金",
    confidence: 0.85,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "阪神",
    pattern: "阪神",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "101",
    counterAccountName: "現金",
    confidence: 0.8,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
    note: "阪神電鉄 — 阪神百貨店等と区別が必要",
  },
  {
    name: "近鉄",
    pattern: "近鉄",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "101",
    counterAccountName: "現金",
    confidence: 0.85,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "南海",
    pattern: "南海",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "101",
    counterAccountName: "現金",
    confidence: 0.8,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
    note: "南海電鉄",
  },
  {
    name: "名鉄",
    pattern: "名鉄",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "101",
    counterAccountName: "現金",
    confidence: 0.9,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "西鉄",
    pattern: "西鉄",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "101",
    counterAccountName: "現金",
    confidence: 0.9,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },

  // ── IC cards ──
  {
    name: "Suica",
    pattern: "Suica",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "101",
    counterAccountName: "現金",
    confidence: 0.9,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
    note: "チャージ時の仕訳",
  },
  {
    name: "PASMO",
    pattern: "PASMO",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "101",
    counterAccountName: "現金",
    confidence: 0.9,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
    note: "チャージ時の仕訳",
  },
  {
    name: "ICOCA",
    pattern: "ICOCA",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "101",
    counterAccountName: "現金",
    confidence: 0.9,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
    note: "チャージ時の仕訳",
  },
  {
    name: "manaca",
    pattern: "manaca",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "101",
    counterAccountName: "現金",
    confidence: 0.9,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
    note: "チャージ時の仕訳",
  },

  // ── Taxi ──
  {
    name: "日本交通",
    pattern: "日本交通",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "101",
    counterAccountName: "現金",
    confidence: 0.9,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
    note: "タクシー大手",
  },
  {
    name: "タクシー",
    pattern: "タクシー",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "101",
    counterAccountName: "現金",
    confidence: 0.9,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "GO(タクシー)",
    pattern: "GO タクシー|GOタクシー",
    matchType: "regex",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
    note: "タクシー配車アプリ GO",
  },
  {
    name: "DiDi",
    pattern: "DiDi",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
    note: "DiDi タクシー配車",
  },
  {
    name: "S.RIDE",
    pattern: "S.RIDE|S\\.RIDE",
    matchType: "regex",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
    note: "ソニー系タクシー配車アプリ",
  },

  // ── Ride share ──
  {
    name: "Uber",
    pattern: "Uber",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.85,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
    note: "Uber Taxi — Uber Eats は別勘定",
  },

  // ── Airlines ──
  {
    name: "ANA",
    pattern: "ANA|全日空",
    matchType: "regex",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "JAL",
    pattern: "JAL|日本航空",
    matchType: "regex",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "Peach",
    pattern: "Peach",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.8,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
    note: "Peach Aviation — LCC",
  },
  {
    name: "Jetstar",
    pattern: "Jetstar",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
    note: "ジェットスター — LCC",
  },
  {
    name: "スカイマーク",
    pattern: "スカイマーク",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "スターフライヤー",
    pattern: "スターフライヤー",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "ソラシドエア",
    pattern: "ソラシドエア",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },

  // ── Gas stations ──
  {
    name: "ENEOS",
    pattern: "ENEOS",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
    note: "車両燃料費 — 車両費として分類する場合もあり",
  },
  {
    name: "出光",
    pattern: "出光",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
    note: "出光興産",
  },
  {
    name: "コスモ",
    pattern: "コスモ石油|コスモ",
    matchType: "regex",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.8,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
    note: "コスモ石油",
  },
  {
    name: "昭和シェル",
    pattern: "昭和シェル",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
    note: "出光昭和シェル",
  },
  {
    name: "キグナス",
    pattern: "キグナス",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
    note: "キグナス石油",
  },
  {
    name: "ニコニコステーション",
    pattern: "ニコニコステーション",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "apollostation",
    pattern: "apollostation",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
    note: "出光興産の新ブランド",
  },

  // ── Parking ──
  {
    name: "タイムズ",
    pattern: "タイムズ",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.85,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
    note: "タイムズ駐車場",
  },
  {
    name: "三井のリパーク",
    pattern: "三井のリパーク|リパーク",
    matchType: "regex",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "NPC24H",
    pattern: "NPC24H|NPC",
    matchType: "regex",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.85,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
    note: "日本パーキング",
  },

  // ── ETC ──
  {
    name: "ETC",
    pattern: "ETC",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
    note: "高速道路料金",
  },

  // ── Highway bus ──
  {
    name: "高速バス",
    pattern: "高速バス",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "WILLER",
    pattern: "WILLER",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
    note: "WILLER EXPRESS 高速バス",
  },

  // ── Car rental ──
  {
    name: "トヨタレンタカー",
    pattern: "トヨタレンタカー",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "ニッポンレンタカー",
    pattern: "ニッポンレンタカー",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "オリックスレンタカー",
    pattern: "オリックスレンタカー",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "タイムズカーレンタル",
    pattern: "タイムズカーレンタル|タイムズカー",
    matchType: "regex",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },

  // ── Bike share ──
  {
    name: "ドコモバイクシェア",
    pattern: "ドコモバイクシェア",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "HELLO CYCLING",
    pattern: "HELLO CYCLING",
    matchType: "contains",
    accountCode: "511",
    accountName: "旅費交通費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
];
