// This file is part of kanjokamoku — MIT License
// https://github.com/tsubasagit/kanjokamoku

import type { ClassificationRule } from "./types";

/**
 * 水道光熱費 → 水道光熱費(520)
 * 電力会社・ガス会社・水道局からの請求を分類する。
 * counterAccount: 普通預金(102) — 口座振替が一般的
 */
export const UTILITY_RULES: ClassificationRule[] = [
  // ── 電力 ──
  {
    name: "東京電力",
    pattern: "東京電力",
    matchType: "contains",
    accountCode: "520",
    accountName: "水道光熱費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    note: "東京電力エナジーパートナー",
  },
  {
    name: "関西電力",
    pattern: "関西電力",
    matchType: "contains",
    accountCode: "520",
    accountName: "水道光熱費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
  },
  {
    name: "中部電力",
    pattern: "中部電力",
    matchType: "contains",
    accountCode: "520",
    accountName: "水道光熱費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
  },
  {
    name: "東北電力",
    pattern: "東北電力",
    matchType: "contains",
    accountCode: "520",
    accountName: "水道光熱費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
  },
  {
    name: "九州電力",
    pattern: "九州電力",
    matchType: "contains",
    accountCode: "520",
    accountName: "水道光熱費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
  },
  {
    name: "北海道電力",
    pattern: "北海道電力",
    matchType: "contains",
    accountCode: "520",
    accountName: "水道光熱費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
  },
  {
    name: "四国電力",
    pattern: "四国電力",
    matchType: "contains",
    accountCode: "520",
    accountName: "水道光熱費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
  },
  {
    name: "中国電力",
    pattern: "中国電力",
    matchType: "contains",
    accountCode: "520",
    accountName: "水道光熱費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
  },
  {
    name: "北陸電力",
    pattern: "北陸電力",
    matchType: "contains",
    accountCode: "520",
    accountName: "水道光熱費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
  },
  {
    name: "沖縄電力",
    pattern: "沖縄電力",
    matchType: "contains",
    accountCode: "520",
    accountName: "水道光熱費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
  },
  {
    name: "Looopでんき",
    pattern: "Looop",
    matchType: "contains",
    accountCode: "520",
    accountName: "水道光熱費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.9,
    note: "新電力 Looopでんき",
  },
  {
    name: "楽天でんき",
    pattern: "楽天でんき",
    matchType: "contains",
    accountCode: "520",
    accountName: "水道光熱費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    note: "楽天エナジー",
  },
  {
    name: "auでんき",
    pattern: "auでんき",
    matchType: "contains",
    accountCode: "520",
    accountName: "水道光熱費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    note: "KDDI auでんき",
  },
  {
    name: "ENEOSでんき",
    pattern: "ENEOSでんき",
    matchType: "contains",
    accountCode: "520",
    accountName: "水道光熱費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
  },
  {
    name: "ソフトバンクでんき",
    pattern: "ソフトバンクでんき",
    matchType: "contains",
    accountCode: "520",
    accountName: "水道光熱費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
  },

  // ── ガス ──
  {
    name: "東京ガス",
    pattern: "東京ガス",
    matchType: "contains",
    accountCode: "520",
    accountName: "水道光熱費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
  },
  {
    name: "大阪ガス",
    pattern: "大阪ガス",
    matchType: "contains",
    accountCode: "520",
    accountName: "水道光熱費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
  },
  {
    name: "東邦ガス",
    pattern: "東邦ガス",
    matchType: "contains",
    accountCode: "520",
    accountName: "水道光熱費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
  },
  {
    name: "西部ガス",
    pattern: "西部ガス",
    matchType: "contains",
    accountCode: "520",
    accountName: "水道光熱費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
  },
  {
    name: "北海道ガス",
    pattern: "北海道ガス",
    matchType: "contains",
    accountCode: "520",
    accountName: "水道光熱費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
  },
  {
    name: "京葉ガス",
    pattern: "京葉ガス",
    matchType: "contains",
    accountCode: "520",
    accountName: "水道光熱費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
  },
  {
    name: "静岡ガス",
    pattern: "静岡ガス",
    matchType: "contains",
    accountCode: "520",
    accountName: "水道光熱費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
  },
  {
    name: "ENEOSガス",
    pattern: "ENEOSガス",
    matchType: "contains",
    accountCode: "520",
    accountName: "水道光熱費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
  },
  {
    name: "東急ガス",
    pattern: "東急ガス",
    matchType: "contains",
    accountCode: "520",
    accountName: "水道光熱費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
  },

  // ── 水道 ──
  {
    name: "水道局",
    pattern: "水道局",
    matchType: "contains",
    accountCode: "520",
    accountName: "水道光熱費",
    counterAccountCode: "102",
    counterAccountName: "普通預金",
    confidence: 0.95,
    note: "各自治体の水道局",
  },
];
