// This file is part of kanjokamoku — MIT License
// https://github.com/tsubasagit/kanjokamoku

import type { ClassificationRule } from "./types";

/**
 * Webインフラ関連 → 通信費(512)
 * ドメイン・CDN・SSL・Webサイトビルダーを分類する。
 * counterAccount: クレジットカード(203)
 */
export const WEB_INFRA_RULES: ClassificationRule[] = [
  // ── ドメイン ──
  {
    name: "お名前.com",
    pattern: "お名前.com",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "GMOインターネット ドメイン登録",
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "ムームードメイン",
    pattern: "ムームードメイン",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "GMOペパボ ドメイン登録",
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "スタードメイン",
    pattern: "スタードメイン",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "ネットオウル ドメイン登録",
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "Google Domains",
    pattern: "Google Domains",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "Squarespace Domainsに移管済み",
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "Gandi",
    pattern: "Gandi",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    note: "Gandi.net ドメイン登録",
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },

  // ── CDN ──
  {
    name: "Cloudflare",
    pattern: "Cloudflare",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "CDN / DNS / セキュリティ",
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "Akamai",
    pattern: "Akamai",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "Fastly",
    pattern: "Fastly",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "Amazon CloudFront",
    pattern: "CloudFront",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    note: "AWS CloudFront CDN",
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },

  // ── SSL証明書 ──
  {
    name: "GlobalSign",
    pattern: "GlobalSign",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "SSL/TLS証明書",
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "DigiCert",
    pattern: "DigiCert",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "SSL/TLS証明書",
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "Let's Encrypt",
    pattern: "Let's Encrypt",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    note: "無料SSL — 寄付の場合あり",
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },

  // ── Webサイトビルダー ──
  {
    name: "Wix",
    pattern: "Wix",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.9,
    note: "Wix.com Webサイトビルダー",
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "Jimdo",
    pattern: "Jimdo",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "Squarespace",
    pattern: "Squarespace",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "BASE",
    pattern: "BASE",
    matchType: "exact",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.75,
    note: "BASEネットショップ — 短い名称のため exact match",
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "STORES",
    pattern: "STORES",
    matchType: "exact",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.8,
    note: "STORES.jp ネットショップ/決済",
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
  {
    name: "Shopify",
    pattern: "Shopify",
    matchType: "contains",
    accountCode: "512",
    accountName: "通信費",
    counterAccountCode: "203",
    counterAccountName: "クレジットカード",
    confidence: 0.95,
    note: "ECプラットフォーム",
    consumptionTaxClass: "課税仕入10%",
    invoiceRequired: true,
  },
];
